apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-brain
  labels:
    app: django-brain
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-brain
  template:
    metadata:
      labels:
        app: django-brain
    spec:
      containers:
        - image: elkis/brain_ai:latest
          name: django-brain
          ports:
            - containerPort: 8001
  
---

apiVersion: v1
kind: Service
metadata:
  name: django-brain
  labels:
    app: django-brain
spec:
  type: NodePort
  selector:
    app: django-brain
  ports:
    - port: 8001
      targetPort: 8001